# Essential ESPHome config options
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: "2023.12.0"
  on_boot:
    then:
      # Wakes up the desk and reports height
      - uart.write:
          id: handset_tx
          data: [ 0x0 ]
  project:
    name: tj_horner.upsy_desky
    version: "2.0.0"
  platformio_options:
    board_build.mcu: esp32c3
    board_build.flash_mode: dio

uart:
  id: handset_tx
  tx_pin: 21        # 16 (4) - TX
  baud_rate: 9600

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Configurable options
substitutions:
  name: "upsy-desky"
  friendly_name: "Upsy Desky"
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height"

  # Standing Desk Component Config
  standing_desk_uart_rx_pin: "20"     # 17 (2) - RX
  standing_desk_up_pin: "4"           # 21 (7) - MOVE UP
  standing_desk_down_pin: "5"         # 22 (8) - MVOE DOWN
  standing_desk_min_height: "25.2"
  standing_desk_max_height: "50.8"

  # Presets Addon Config
  button_bit1_pin: "4"   # 21 (7)
  button_bit2_pin: "5"   # 22 (8)
  button_bit4_pin: "6"   # 19 (6) - MEMORY RECALL
  button_m_pin: "3"      # 18 (1) - M Button

  # Runtime Config Defaults
  default_height_units: "in" # Must be "in" or "cm"

  standing_desk_variant: "uplift"

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  addon_presets: !include addons/presets.yaml
  addon_stable_ids: !include addons/stable-ids.yaml
  addon_runtime_config: !include addons/runtime-config.yaml

button:
  - platform: restart
    name: "Restart"

light:
  - platform: status_led
    id: upsy_desky_status_led
    name: "Status LED"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON
